"""Remove TOTP fields and add video metadata fields

Revision ID: 5c258263c971
Revises: adb7ee20c2cd
Create Date: 2025-09-27 23:21:34.653810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c258263c971'
down_revision = 'adb7ee20c2cd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('video_records', 'tags',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.drop_index('ix_video_records_is_deleted', table_name='video_records')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_video_records_is_deleted', 'video_records', ['is_deleted'], unique=False)
    op.alter_column('video_records', 'tags',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###