seed: 1337

data:
  ou_mvlp_gei_dir: "/Users/caldwellwachira/Downloads/__Parent__/__Parent__/GEI"
  uclm_thermal_root: "/Users/caldwellwachira/Downloads/Thermal Image Dataset for Concealed Handgun Detection/UCLM_Thermal_Imaging_Dataset"
  thermal_subdirs:
    handgun: "Handgun"
    no_gun: "No_Gun"
  image_size: 64
  max_train_images: null  
splits:
  train: 0.8
  val: 0.1
  test: 0.1

model:
  latent_dim: 32
  base_channels: 24
  dropout: 0.0

train:
  batch_size: 64
  lr: 0.001
  weight_decay: 0.00001
  epochs: 50
  early_stopping_patience: 7
  num_workers: 4
  scheduler: "cosine"

eval:
  roc_bootstrap_iters: 1000

output_dir: "outputs"

processing:
  clahe_clip:  2.5
  clahe_grid: 8

